<a href="https://colab.research.google.com/github/Shahid0023/CODSOFT/blob/main/Project_02_Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

In [17]:
#Loading Dataset  in variable
cr_data = pd.read_csv('/content/creditcard.csv')

In [18]:
#Showing 1st 5 rows
cr_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [19]:
#Showing last 5 rows
cr_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [20]:
#Dataset information
cr_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [21]:
#Dataset description
cr_data.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,284807.000000,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,...,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,2.848070e+05,284807.000000,284807.000000
mean,94813.859575,1.168375e-15,3.416908e-16,-1.379537e-15,2.074095e-15,9.604066e-16,1.487313e-15,-5.556467e-16,1.213481e-16,-2.406331e-15,...,1.654067e-16,-3.568593e-16,2.578648e-16,4.473266e-15,5.340915e-16,1.683437e-15,-3.660091e-16,-1.227390e-16,88.349619,0.001727
std,47488.145955,1.958696e+00,1.651309e+00,1.516255e+00,1.415869e+00,1.380247e+00,1.332271e+00,1.237094e+00,1.194353e+00,1.098632e+00,...,7.345240e-01,7.257016e-01,6.244603e-01,6.056471e-01,5.212781e-01,4.822270e-01,4.036325e-01,3.300833e-01,250.120109,0.041527
min,0.000000,-5.640751e+01,-7.271573e+01,-4.832559e+01,-5.683171e+00,-1.137433e+02,-2.616051e+01,-4.355724e+01,-7.321672e+01,-1.343407e+01,...,-3.483038e+01,-1.093314e+01,-4.480774e+01,-2.836627e+00,-1.029540e+01,-2.604551e+00,-2.256568e+01,-1.543008e+01,0.000000,0.000000
25%,54201.500000,-9.203734e-01,-5.985499e-01,-8.903648e-01,-8.486401e-01,-6.915971e-01,-7.682956e-01,-5.540759e-01,-2.086297e-01,-6.430976e-01,...,-2.283949e-01,-5.423504e-01,-1.618463e-01,-3.545861e-01,-3.171451e-01,-3.269839e-01,-7.083953e-02,-5.295979e-02,5.600000,0.000000
50%,84692.000000,1.810880e-02,6.548556e-02,1.798463e-01,-1.984653e-02,-5.433583e-02,-2.741871e-01,4.010308e-02,2.235804e-02,-5.142873e-02,...,-2.945017e-02,6.781943e-03,-1.119293e-02,4.097606e-02,1.659350e-02,-5.213911e-02,1.342146e-03,1.124383e-02,22.000000,0.000000
75%,139320.500000,1.315642e+00,8.037239e-01,1.027196e+00,7.433413e-01,6.119264e-01,3.985649e-01,5.704361e-01,3.273459e-01,5.971390e-01,...,1.863772e-01,5.285536e-01,1.476421e-01,4.395266e-01,3.507156e-01,2.409522e-01,9.104512e-02,7.827995e-02,77.165000,0.000000
max,172792.000000,2.454930e+00,2.205773e+01,9.382558e+00,1.687534e+01,3.480167e+01,7.330163e+01,1.205895e+02,2.000721e+01,1.559499e+01,...,2.720284e+01,1.050309e+01,2.252841e+01,4.584549e+00,7.519589e+00,3.517346e+00,3.161220e+01,3.384781e+01,25691.160000,1.000000

In [23]:
#checking for null values
cr_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [25]:
#Class distribution 0 reperesents normal transactions and 1 reperesents fraud transactions
cr_data['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [26]:
# As we can see the dataset is very un-balanced here we take a sample data from the normal count and store is in a variable
normaltransaction = cr_data[cr_data.Class==0]
fraudtransaction = cr_data[cr_data.Class==1]

In [28]:
#shape attribute of dataset shows total no of rows and columns in the dataset
print(normaltransaction.shape)
print(fraudtransaction.shape)

(284315, 31)
(492, 31)

In [29]:
# statistical veiw of the dataset
normaltransaction.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [30]:
fraudtransaction.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [31]:
#The dataset is very un-balanced so we will take a sample data from normaltransaction dataset for training
# we will take same numbers of rows from normaltransaction as fraudtransaction are 492 but randomly
normal_sample = normaltransaction.sample(n=492)

In [32]:
#lets check the sample dataset / you can see the data is ramdom
normal_sample.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
52602,45551.0,-1.984124,0.193889,0.560990,-0.562712,0.421506,-0.089439,0.974425,0.323495,-1.057247,...,-0.440076,-1.650722,-0.352503,-0.849576,0.187195,-0.166192,-0.044172,-0.328090,189.95,0
229732,146028.0,-0.765082,0.082428,-1.053168,-1.623409,2.150189,-1.589715,1.071386,-0.612510,-0.023814,...,0.087727,0.638553,-0.679179,-0.824981,-0.259740,0.982068,0.025173,0.085769,27.83,0
164465,116735.0,0.394781,-0.537086,0.495576,-2.566372,-0.744379,-0.254445,-0.485483,-0.073244,-1.627469,...,-0.086456,0.155270,0.032334,0.548720,-0.462764,-0.284775,-0.065732,0.005497,14.20,0
141678,84461.0,-0.919878,0.626572,0.889762,-2.065616,-0.214887,-0.122297,-0.222928,0.461967,1.383627,...,0.094983,0.245265,-0.305827,-0.997553,-0.132529,-0.845008,-0.156416,0.057533,1.00,0
241234,150938.0,2.050853,0.070374,-1.303511,0.321399,0.177402,-1.041865,0.266686,-0.367966,0.396799,...,0.280825,0.994970,0.073310,1.152181,0.260717,-0.165298,-0.014006,-0.046231,1.79,0

In [33]:
#you can see by 1st column the data is ramdom
normal_sample.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
42163,40977.0,-1.666317,0.710369,1.027251,-1.167446,-0.339933,1.360794,-1.342611,-1.813582,0.354891,...,-1.449191,-0.089947,-0.095335,-1.286584,-0.118296,0.884397,-0.057955,-0.029823,63.22,0
155088,104456.0,-0.498383,0.817126,2.400030,-0.115925,0.135708,-0.276661,0.508715,-0.241983,1.535676,...,-0.305409,-0.422070,-0.296660,-0.120496,0.244794,-0.724305,-0.077426,-0.146621,2.12,0
278626,168327.0,1.943807,-0.492268,-0.370534,0.317224,-0.556206,0.099278,-0.791658,0.194152,1.256116,...,0.292436,1.023995,0.115920,0.788377,-0.073968,-0.208779,0.031049,-0.041177,8.14,0
178804,123789.0,0.929459,-1.518984,-2.573607,1.488143,0.308366,-0.491472,1.386169,-0.401470,-0.447997,...,0.515518,0.226831,-0.477315,0.724038,0.224832,-0.594107,-0.146959,0.031482,572.76,0
279057,168617.0,1.938311,-0.700294,0.159837,0.289565,-1.283755,-0.302289,-1.145471,0.290490,1.453391,...,0.061310,0.210317,0.352945,0.044019,-0.712658,0.464426,-0.028619,-0.053117,1.00,0

In [34]:
#Same row count as fraud data
print(normal_sample.shape)

(492, 31)

In [35]:
#now we will concat both of the datasents into one sinlge dataset to go for training
final_dataset = pd.concat([normal_sample,fraudtransaction],axis=0)

In [36]:
print(final_dataset.shape)

(984, 31)

In [38]:
#now check for value count by class again
final_dataset['Class'].value_counts()

0    492
1    492
Name: Class, dtype: int64

In [40]:
final_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94001.886179,0.048692,-0.104592,0.002279,0.012225,-0.071053,0.032093,-0.094481,0.090597,0.037624,...,-0.028988,0.013036,0.004830,-0.016747,0.000693,-0.010998,-0.005856,-0.005511,-0.011396,91.606545
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [42]:
#Splitting data into X and Y / Target data and dependancies
X = final_dataset.drop(columns='Class',axis = 1)
Y = final_dataset['Class']

In [43]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
52602    45551.0 -1.984124  0.193889  0.560990 -0.562712  0.421506 -0.089439
229732  146028.0 -0.765082  0.082428 -1.053168 -1.623409  2.150189 -1.589715
164465  116735.0  0.394781 -0.537086  0.495576 -2.566372 -0.744379 -0.254445
141678   84461.0 -0.919878  0.626572  0.889762 -2.065616 -0.214887 -0.122297
241234  150938.0  2.050853  0.070374 -1.303511  0.321399  0.177402 -1.041865
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
52602   0.974425  0.323495 -1.057247  ... -0.164882 -0.440076 -1.650722
229732  1.071386 -0.612510 -0.023814  ... -0.444300  0.087727  0.638553
164465 -0.485483 -0.073244 -1.627469  ... -0.407163 -0.086456  0.155270
141678 -0.222928  0.461967  1.383627  ... -0.265715  0.094983  0.245265
241234  0.266686 -0.367966  0.396799  ... -0.164130  0.280825  0.994970
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
52602  -0.352503 -0.849576  0.187195 -0.166192 -0.044172 -0.328090  189.95
229732 -0.679179 -0.824981 -0.259740  0.982068  0.025173  0.085769   27.83
164465  0.032334  0.548720 -0.462764 -0.284775 -0.065732  0.005497   14.20
141678 -0.305827 -0.997553 -0.132529 -0.845008 -0.156416  0.057533    1.00
241234  0.073310  1.152181  0.260717 -0.165298 -0.014006 -0.046231    1.79
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [44]:
print(Y)

52602     0
229732    0
164465    0
141678    0
241234    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [48]:
#Lets train our dataset
X_train, X_test, Y_train, Y_test  = train_test_split(X,Y,test_size=0.2 , stratify=Y, random_state=2 )

In [49]:
#now print the shape
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

In [50]:
# Model training with logistic regression
cModel = LogisticRegression()

In [51]:
cModel.fit(X_train,Y_train)

LogisticRegression()

In [53]:
#Evaluation & accuracy core checking with train data
X_tainPred= cModel.predict(X_train)
X_train_AccScore = accuracy_score(X_tainPred,Y_train)

In [54]:
print('Accuracy with Training data : ', X_train_AccScore)

Accuracy with Training data :  0.9491740787801779

In [55]:
#Evaluation & accuracy core checking with test data
X_testPred = cModel.predict(X_test)
X_test_AccScore = accuracy_score(X_testPred,Y_test)

In [56]:
print('Accuracy with Testing data : ', X_test_AccScore)

Accuracy with Testing data :  0.9289340101522843

In [57]:
print(classification_report(Y_test,X_testPred))

              precision    recall  f1-score   support

           0       0.92      0.94      0.93        99
           1       0.94      0.92      0.93        98

    accuracy                           0.93       197
   macro avg       0.93      0.93      0.93       197
weighted avg       0.93      0.93      0.93       197